### ISSUE TITLE
ML document is disappeared

### ISSUE THREAD

**Issue by jormal** [Z3Prover/z3prover.github.io#3]
Hi.
I usually reference the document for ML binding in [here](https://z3prover.github.io/api/html/ml/Z3.html)
But, this page has a 404 error someday after.
Is there any recovery plan?

**Comment by NikolajBjorner** [comment]
@jormal, @c-cube - I have been trying to build ocaml doc with our pipelines so documentation can be updated.
Unfortunately, the cloud script fails and I can't immediately see why it would fail. 
Both https://github.com/Z3Prover/z3/blob/b11203e2d28cb30adaeba3b8c0923c190dbe64e5/azure-pipelines.yml#L66
and https://github.com/Z3Prover/z3/blob/b11203e2d28cb30adaeba3b8c0923c190dbe64e5/scripts/nightly.yaml#L61
have been updated in somewhat different ways (the latter trying to see if there is something with the ocaml environment that needs to be set). They both fail to bind the module "Z" (from zarith) even thought the ocamldoc command-line includes the -I +zarith as prescribed.
It would be great if you have an idea of what can be done about it.

**Comment by c-cube** [comment]
I haven't used ocamldoc in years (these days people use [odoc](https://github.com/ocaml/odoc/) alongside a build system like `dune`). I suppose `+zarith` doesn't work because it's not a directory of the compiler distribution; what about `-I $( ocamlfind query zarith )` to ask for the location of zarith?

**Comment by jormal** [comment]
It works! Thanks :)
